services:
  - type: web
    name: syntaxsocial-web
    env: static
    buildCommand:  npm i &&  npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
